name: "$(finalAction) - Azure Platform"

trigger:
  batch: true
  branches:
    include:
      - master

pr:
  - master

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
    - plan
    - apply
    - destroy

  - name: environment_components
    type: object
    default:
    - deployment: 'stg_gaps2'
      environment: 'stg'
      component: 'gaps2'
      service_connection: 'dts-heritage-intsvc-stg'
      storage_account_rg: 'core-infra-stg-rg'
      storage_account_name: 'cftappsstg'
      dependsOn: 'Precheck'

    - deployment: 'prod_gaps2'
      environment: 'prod'
      component: 'gaps2'
      service_connection: 'dts-heritage-intsvc-prod'
      storage_account_rg: 'core-infra-prod-rg'
      storage_account_name: 'cftappsprod'
      dependsOn: 'stg_gaps2'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentImage
    value: ubuntu-latest
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: gaps2
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries
  - name: finalAction
    ${{ if and(in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master'), in(variables['Build.Reason'], 'BatchedCI', 'IndividualCI', 'PullRequest', 'Schedule'))  }}:
      value: 'apply'
    ${{ else }}:
      value: ${{ parameters.overrideAction }}


stages:
  - stage: Precheck
    jobs:
      - job:
        pool:
          vmImage: ${{ variables.agentImage }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'azurerm-sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool:
            vmImage: ${{ variables.agentImage }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
            - template: steps/terraform.yaml@cnp-azuredevops-libraries
              parameters:
                overrideAction: ${{ parameters.overrideAction }}
                environment: ${{ deployment.environment }}
                component: ${{ deployment.component }}
                serviceConnection: ${{ deployment.service_connection }}
                terraformInitSubscription: ${{ variables.terraformInitSubscription }}
                product: ${{ variables.product }}
                planCommandOptions:
                  -compact-warnings
